name:               cpp-dependencies
version:            '0.0.1'
summary:            cpp-dependencies
description:        |
  cpp-dependencies

grade:              stable
confinement:        strict
# icon:               snap/../assets/logo/crown.svg

apps:
  cpp-dependencies:
    command:        cpp-dependencies
    plugs:
      - home

parts:
  cpp-depenencies:
    # source: .
    source: https://github.com/tomtom-international/cpp-dependencies.git
    plugin: cmake
    build-packages:
      - build-essential
      - libboost-filesystem-dev
      - libboost-system-dev
      # - doxygen
      # - graphviz
